= GStreamer Depth Meta

// tag::depth_meta[]

[[rgbd_caps]]
== Custom video/rgbd CAPS

This format allows *synchronised transport of multiple streams under a
single stream in GStreamer.*

=== depth-meta

Internally, gst-depth-meta and its
https://gitlab.com/aivero/public/gstreamer/gst-depth-meta-rs[Rust
wrapper] are utilised to attach additional frames to the stream.

The `video/rgbd` format in GStreamer relies on two different kinds of
metadata:

[arabic]
. `BufferMeta`, which allows developers to add buffers as metadata onto
buffers
. `TagsMeta`, which allows developers to add tags (strings) as metadata
onto buffers. This may be used to identify the buffer later downstream.

One of the enabled streams is considered to be the _“main”_ stream as it
is transported in the *main buffer*. All additional streams are embedded
in `BufferMeta` of the _“main”_ buffer utilising
link:depth_meta[gst-depth-meta].

Furthermore, link:depth_meta[gst-depth-meta] is utilised to attach a
*tag title* to each buffer (main and all additional buffers) that is
used by other elements to identify each buffer. Said tag is attached
using the `TagsMeta`.

==== Example Buffer Structure

The following structure outlines how buffers can be tagged and stacked,
which is how [.title-ref]#video/rgbd# is implemented. The example is
given using JSON, as it gives a decent overview of the content of the
buffers:

[source,sourceCode,json]
----
{
    "TagsMeta": [ { "Title": "depth" } ],
    "BufferMeta": [
        { "TagsMeta": [ { "Title": "infra1" } ] },
        { "TagsMeta": [ { "Title": "color" } ] }
    ]
}
----

=== video/rgbd CAPS

All pads that transport a `video/rgbd` stream must utilise the custom
`video/rgbd` CAPS type. These caps always contain the following fields:

* *streams:* A comma-separated string of streams that are present. The
first stream is considered to be the “main” stream and is therefore
transported in the main buffer. There must always be at least one stream
enabled. All additional streams are attached as meta to the main buffer.
The following priority is currently applied for video/rgbd streams: `depth > infra1 > infra2 > color`, meaning that
if there is a `depth` stream, it will always be the main stream. If only `infra1` and `color` are available, `infra1` will be
the main stream.
* *%s_format:* Format for each selected stream, e.g.
`depth_format="Gray16_LE"`.
* *%s_width:* Width for each selected stream, e.g. `depth_width=1280`.
* *%s_height:* Height for each selected stream, e.g. `depth_height=720`.
* *framerate:* Common framerate for all selected streams, e.g.
`framerate=30/1`.

Each buffer in `video/rgbd` CAPS transport contains the following:

* Frame data for *main stream*, typically the _depth_ stream.
* A full GstBuffer for each *auxiliary stream*, e.g. _color_ or any of the meta streams.

The buffers for all *auxiliary streams* are attached to the GstBuffer for the *main stream* by the use of `BufferMeta`
described in xref:depthmeta:ROOT:page$depth-meta.adoc[Depth Meta]. Furthermore, all buffers, both for *main stream*
and *auxiliary streams*, are tagged accordingly using the `TagsMeta`.

The `video/rgbd` is not formally defined in any of the GStreamer
elements, but simply emerges because we have implemented as series of
elements that accept and operate on `video/rgbd` CAPS.

// end::depth_meta[]