#!/usr/bin/env python3
import sys
import os

# Append repo root to python path
sys.path.append(os.getcwd())
from contrib.scripts import util

# Checkout submodules
branch = util.call("git", ["branch", "--show-current"])[:-1]
util.call("git", ["submodule", "foreach", "git", "checkout", "-B", branch])

# Only create aliases for new branches
if branch == "master" or sys.argv[1] != sys.argv[2]:
    exit(0)

# Find branches
(branch, old_branch) = util.find_branches()

# Set fallback commit, if package is not available local or remote
commit = util.call("git", ["rev-parse", "HEAD"])

# Create aliases
util.create_aliases(commit, branch, old_branch, "aivero-all")
